/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:58269ab8-0017-4027-b945-f305cd7e19c8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_3QqAGcn63",
    "aws_user_pools_web_client_id": "dgqbfv7alj09oqob91f162dh4",
    "oauth": {
        "domain": "appdemo-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "projectdemo75da331a319f45a9a34b844f385b606d162213-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "predictions": {
        "identify": {
            "identifyLabels": {
                "proxy": false,
                "region": "ap-south-1",
                "defaults": {
                    "type": "LABELS"
                }
            }
        }
    },
    "Storage": {
        "AWSS3": {
            "bucket": "projectdemo75da331a319f45a9a34b844f385b606d162213-dev",
            "region": "ap-south-1"
        }
    }
};


export default awsmobile;
